import { Fragment, useState } from "react";
import { classNames } from "~/utils";
import { Listbox, Transition } from "@headlessui/react";
import {
  AcademicCapIcon,
  AdjustmentsHorizontalIcon,
  AdjustmentsVerticalIcon,
  ArchiveBoxArrowDownIcon,
  ArchiveBoxXMarkIcon,
  ArchiveBoxIcon,
  ArrowDownCircleIcon,
  ArrowDownLeftIcon,
  ArrowDownOnSquareStackIcon,
  ArrowDownOnSquareIcon,
  ArrowDownRightIcon,
  ArrowDownTrayIcon,
  ArrowDownIcon,
  ArrowLeftCircleIcon,
  ArrowLeftOnRectangleIcon,
  ArrowLeftIcon,
  ArrowLongDownIcon,
  ArrowLongLeftIcon,
  ArrowLongRightIcon,
  ArrowLongUpIcon,
  ArrowPathRoundedSquareIcon,
  ArrowPathIcon,
  ArrowRightCircleIcon,
  ArrowRightOnRectangleIcon,
  ArrowRightIcon,
  ArrowSmallDownIcon,
  ArrowSmallLeftIcon,
  ArrowSmallRightIcon,
  ArrowSmallUpIcon,
  ArrowTopRightOnSquareIcon,
  ArrowTrendingDownIcon,
  ArrowTrendingUpIcon,
  ArrowUpCircleIcon,
  ArrowUpLeftIcon,
  ArrowUpOnSquareStackIcon,
  ArrowUpOnSquareIcon,
  ArrowUpRightIcon,
  ArrowUpTrayIcon,
  ArrowUpIcon,
  ArrowUturnDownIcon,
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  ArrowUturnUpIcon,
  ArrowsPointingInIcon,
  ArrowsPointingOutIcon,
  ArrowsRightLeftIcon,
  ArrowsUpDownIcon,
  AtSymbolIcon,
  BackspaceIcon,
  BackwardIcon,
  BanknotesIcon,
  Bars2Icon,
  Bars3BottomLeftIcon,
  Bars3BottomRightIcon,
  Bars3CenterLeftIcon,
  Bars3Icon,
  Bars4Icon,
  BarsArrowDownIcon,
  BarsArrowUpIcon,
  Battery0Icon,
  Battery100Icon,
  Battery50Icon,
  BeakerIcon,
  BellAlertIcon,
  BellSlashIcon,
  BellSnoozeIcon,
  BellIcon,
  BoltSlashIcon,
  BoltIcon,
  BookOpenIcon,
  BookmarkSlashIcon,
  BookmarkSquareIcon,
  BookmarkIcon,
  BriefcaseIcon,
  BugAntIcon,
  BuildingLibraryIcon,
  BuildingOffice2Icon,
  BuildingOfficeIcon,
  BuildingStorefrontIcon,
  CakeIcon,
  CalculatorIcon,
  CalendarDaysIcon,
  CalendarIcon,
  CameraIcon,
  ChartBarSquareIcon,
  ChartBarIcon,
  ChartPieIcon,
  ChatBubbleBottomCenterTextIcon,
  ChatBubbleBottomCenterIcon,
  ChatBubbleLeftEllipsisIcon,
  ChatBubbleLeftRightIcon,
  ChatBubbleLeftIcon,
  ChatBubbleOvalLeftEllipsisIcon,
  ChatBubbleOvalLeftIcon,
  CheckBadgeIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDoubleDownIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ChevronDoubleUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpDownIcon,
  ChevronUpIcon,
  CircleStackIcon,
  ClipboardDocumentCheckIcon,
  ClipboardDocumentListIcon,
  ClipboardDocumentIcon,
  ClipboardIcon,
  ClockIcon,
  CloudArrowDownIcon,
  CloudArrowUpIcon,
  CloudIcon,
  CodeBracketSquareIcon,
  CodeBracketIcon,
  Cog6ToothIcon,
  Cog8ToothIcon,
  CogIcon,
  CommandLineIcon,
  ComputerDesktopIcon,
  CpuChipIcon,
  CreditCardIcon,
  CubeTransparentIcon,
  CubeIcon,
  CurrencyBangladeshiIcon,
  CurrencyDollarIcon,
  CurrencyEuroIcon,
  CurrencyPoundIcon,
  CurrencyRupeeIcon,
  CurrencyYenIcon,
  CursorArrowRaysIcon,
  CursorArrowRippleIcon,
  DevicePhoneMobileIcon,
  DeviceTabletIcon,
  DocumentArrowDownIcon,
  DocumentArrowUpIcon,
  DocumentChartBarIcon,
  DocumentCheckIcon,
  DocumentDuplicateIcon,
  DocumentMagnifyingGlassIcon,
  DocumentMinusIcon,
  DocumentPlusIcon,
  DocumentTextIcon,
  DocumentIcon,
  EllipsisHorizontalCircleIcon,
  EllipsisHorizontalIcon,
  EllipsisVerticalIcon,
  EnvelopeOpenIcon,
  EnvelopeIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  EyeDropperIcon,
  EyeSlashIcon,
  EyeIcon,
  FaceFrownIcon,
  FaceSmileIcon,
  FilmIcon,
  FingerPrintIcon,
  FireIcon,
  FlagIcon,
  FolderArrowDownIcon,
  FolderMinusIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  FolderIcon,
  ForwardIcon,
  FunnelIcon,
  GifIcon,
  GiftTopIcon,
  GiftIcon,
  GlobeAltIcon,
  GlobeAmericasIcon,
  GlobeAsiaAustraliaIcon,
  GlobeEuropeAfricaIcon,
  HandRaisedIcon,
  HandThumbDownIcon,
  HandThumbUpIcon,
  HashtagIcon,
  HeartIcon,
  HomeModernIcon,
  HomeIcon,
  IdentificationIcon,
  InboxArrowDownIcon,
  InboxStackIcon,
  InboxIcon,
  InformationCircleIcon,
  KeyIcon,
  LanguageIcon,
  LifebuoyIcon,
  LightBulbIcon,
  LinkIcon,
  ListBulletIcon,
  LockClosedIcon,
  LockOpenIcon,
  MagnifyingGlassCircleIcon,
  MagnifyingGlassMinusIcon,
  MagnifyingGlassPlusIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MapIcon,
  MegaphoneIcon,
  MicrophoneIcon,
  MinusCircleIcon,
  MinusSmallIcon,
  MinusIcon,
  MoonIcon,
  MusicalNoteIcon,
  NewspaperIcon,
  NoSymbolIcon,
  PaintBrushIcon,
  PaperAirplaneIcon,
  PaperClipIcon,
  PauseCircleIcon,
  PauseIcon,
  PencilSquareIcon,
  PencilIcon,
  PhoneArrowDownLeftIcon,
  PhoneArrowUpRightIcon,
  PhoneXMarkIcon,
  PhoneIcon,
  PhotoIcon,
  PlayCircleIcon,
  PlayPauseIcon,
  PlayIcon,
  PlusCircleIcon,
  PlusSmallIcon,
  PlusIcon,
  PowerIcon,
  PresentationChartBarIcon,
  PresentationChartLineIcon,
  PrinterIcon,
  PuzzlePieceIcon,
  QrCodeIcon,
  QuestionMarkCircleIcon,
  QueueListIcon,
  RadioIcon,
  ReceiptPercentIcon,
  ReceiptRefundIcon,
  RectangleGroupIcon,
  RectangleStackIcon,
  RocketLaunchIcon,
  RssIcon,
  ScaleIcon,
  ScissorsIcon,
  ServerStackIcon,
  ServerIcon,
  ShareIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SignalSlashIcon,
  SignalIcon,
  SparklesIcon,
  SpeakerWaveIcon,
  SpeakerXMarkIcon,
  Square2StackIcon,
  Square3Stack3DIcon,
  Squares2X2Icon,
  SquaresPlusIcon,
  StarIcon,
  StopCircleIcon,
  StopIcon,
  SunIcon,
  SwatchIcon,
  TableCellsIcon,
  TagIcon,
  TicketIcon,
  TrashIcon,
  TrophyIcon,
  TruckIcon,
  TvIcon,
  UserCircleIcon,
  UserGroupIcon,
  UserMinusIcon,
  UserPlusIcon,
  UserIcon,
  UsersIcon,
  VariableIcon,
  VideoCameraSlashIcon,
  VideoCameraIcon,
  ViewColumnsIcon,
  ViewfinderCircleIcon,
  WalletIcon,
  WifiIcon,
  WindowIcon,
  WrenchScrewdriverIcon,
  WrenchIcon,
  XCircleIcon,
  XMarkIcon,
} from "@heroicons/react/20/solid";

const icons = [
  { component: AcademicCapIcon, name: "AcademicCapIcon" },
  { component: AdjustmentsHorizontalIcon, name: "AdjustmentsHorizontalIcon" },
  { component: AdjustmentsVerticalIcon, name: "AdjustmentsVerticalIcon" },
  { component: ArchiveBoxArrowDownIcon, name: "ArchiveBoxArrowDownIcon" },
  { component: ArchiveBoxXMarkIcon, name: "ArchiveBoxXMarkIcon" },
  { component: ArchiveBoxIcon, name: "ArchiveBoxIcon" },
  { component: ArrowDownCircleIcon, name: "ArrowDownCircleIcon" },
  { component: ArrowDownLeftIcon, name: "ArrowDownLeftIcon" },
  { component: ArrowDownOnSquareStackIcon, name: "ArrowDownOnSquareStackIcon" },
  { component: ArrowDownOnSquareIcon, name: "ArrowDownOnSquareIcon" },
  { component: ArrowDownRightIcon, name: "ArrowDownRightIcon" },
  { component: ArrowDownTrayIcon, name: "ArrowDownTrayIcon" },
  { component: ArrowDownIcon, name: "ArrowDownIcon" },
  { component: ArrowLeftCircleIcon, name: "ArrowLeftCircleIcon" },
  { component: ArrowLeftOnRectangleIcon, name: "ArrowLeftOnRectangleIcon" },
  { component: ArrowLeftIcon, name: "ArrowLeftIcon" },
  { component: ArrowLongDownIcon, name: "ArrowLongDownIcon" },
  { component: ArrowLongLeftIcon, name: "ArrowLongLeftIcon" },
  { component: ArrowLongRightIcon, name: "ArrowLongRightIcon" },
  { component: ArrowLongUpIcon, name: "ArrowLongUpIcon" },
  { component: ArrowPathRoundedSquareIcon, name: "ArrowPathRoundedSquareIcon" },
  { component: ArrowPathIcon, name: "ArrowPathIcon" },
  { component: ArrowRightCircleIcon, name: "ArrowRightCircleIcon" },
  { component: ArrowRightOnRectangleIcon, name: "ArrowRightOnRectangleIcon" },
  { component: ArrowRightIcon, name: "ArrowRightIcon" },
  { component: ArrowSmallDownIcon, name: "ArrowSmallDownIcon" },
  { component: ArrowSmallLeftIcon, name: "ArrowSmallLeftIcon" },
  { component: ArrowSmallRightIcon, name: "ArrowSmallRightIcon" },
  { component: ArrowSmallUpIcon, name: "ArrowSmallUpIcon" },
  { component: ArrowTopRightOnSquareIcon, name: "ArrowTopRightOnSquareIcon" },
  { component: ArrowTrendingDownIcon, name: "ArrowTrendingDownIcon" },
  { component: ArrowTrendingUpIcon, name: "ArrowTrendingUpIcon" },
  { component: ArrowUpCircleIcon, name: "ArrowUpCircleIcon" },
  { component: ArrowUpLeftIcon, name: "ArrowUpLeftIcon" },
  { component: ArrowUpOnSquareStackIcon, name: "ArrowUpOnSquareStackIcon" },
  { component: ArrowUpOnSquareIcon, name: "ArrowUpOnSquareIcon" },
  { component: ArrowUpRightIcon, name: "ArrowUpRightIcon" },
  { component: ArrowUpTrayIcon, name: "ArrowUpTrayIcon" },
  { component: ArrowUpIcon, name: "ArrowUpIcon" },
  { component: ArrowUturnDownIcon, name: "ArrowUturnDownIcon" },
  { component: ArrowUturnLeftIcon, name: "ArrowUturnLeftIcon" },
  { component: ArrowUturnRightIcon, name: "ArrowUturnRightIcon" },
  { component: ArrowUturnUpIcon, name: "ArrowUturnUpIcon" },
  { component: ArrowsPointingInIcon, name: "ArrowsPointingInIcon" },
  { component: ArrowsPointingOutIcon, name: "ArrowsPointingOutIcon" },
  { component: ArrowsRightLeftIcon, name: "ArrowsRightLeftIcon" },
  { component: ArrowsUpDownIcon, name: "ArrowsUpDownIcon" },
  { component: AtSymbolIcon, name: "AtSymbolIcon" },
  { component: BackspaceIcon, name: "BackspaceIcon" },
  { component: BackwardIcon, name: "BackwardIcon" },
  { component: BanknotesIcon, name: "BanknotesIcon" },
  { component: Bars2Icon, name: "Bars2Icon" },
  { component: Bars3BottomLeftIcon, name: "Bars3BottomLeftIcon" },
  { component: Bars3BottomRightIcon, name: "Bars3BottomRightIcon" },
  { component: Bars3CenterLeftIcon, name: "Bars3CenterLeftIcon" },
  { component: Bars3Icon, name: "Bars3Icon" },
  { component: Bars4Icon, name: "Bars4Icon" },
  { component: BarsArrowDownIcon, name: "BarsArrowDownIcon" },
  { component: BarsArrowUpIcon, name: "BarsArrowUpIcon" },
  { component: Battery0Icon, name: "Battery0Icon" },
  { component: Battery100Icon, name: "Battery100Icon" },
  { component: Battery50Icon, name: "Battery50Icon" },
  { component: BeakerIcon, name: "BeakerIcon" },
  { component: BellAlertIcon, name: "BellAlertIcon" },
  { component: BellSlashIcon, name: "BellSlashIcon" },
  { component: BellSnoozeIcon, name: "BellSnoozeIcon" },
  { component: BellIcon, name: "BellIcon" },
  { component: BoltSlashIcon, name: "BoltSlashIcon" },
  { component: BoltIcon, name: "BoltIcon" },
  { component: BookOpenIcon, name: "BookOpenIcon" },
  { component: BookmarkSlashIcon, name: "BookmarkSlashIcon" },
  { component: BookmarkSquareIcon, name: "BookmarkSquareIcon" },
  { component: BookmarkIcon, name: "BookmarkIcon" },
  { component: BriefcaseIcon, name: "BriefcaseIcon" },
  { component: BugAntIcon, name: "BugAntIcon" },
  { component: BuildingLibraryIcon, name: "BuildingLibraryIcon" },
  { component: BuildingOffice2Icon, name: "BuildingOffice2Icon" },
  { component: BuildingOfficeIcon, name: "BuildingOfficeIcon" },
  { component: BuildingStorefrontIcon, name: "BuildingStorefrontIcon" },
  { component: CakeIcon, name: "CakeIcon" },
  { component: CalculatorIcon, name: "CalculatorIcon" },
  { component: CalendarDaysIcon, name: "CalendarDaysIcon" },
  { component: CalendarIcon, name: "CalendarIcon" },
  { component: CameraIcon, name: "CameraIcon" },
  { component: ChartBarSquareIcon, name: "ChartBarSquareIcon" },
  { component: ChartBarIcon, name: "ChartBarIcon" },
  { component: ChartPieIcon, name: "ChartPieIcon" },
  {
    component: ChatBubbleBottomCenterTextIcon,
    name: "ChatBubbleBottomCenterTextIcon",
  },
  { component: ChatBubbleBottomCenterIcon, name: "ChatBubbleBottomCenterIcon" },
  { component: ChatBubbleLeftEllipsisIcon, name: "ChatBubbleLeftEllipsisIcon" },
  { component: ChatBubbleLeftRightIcon, name: "ChatBubbleLeftRightIcon" },
  { component: ChatBubbleLeftIcon, name: "ChatBubbleLeftIcon" },
  {
    component: ChatBubbleOvalLeftEllipsisIcon,
    name: "ChatBubbleOvalLeftEllipsisIcon",
  },
  { component: ChatBubbleOvalLeftIcon, name: "ChatBubbleOvalLeftIcon" },
  { component: CheckBadgeIcon, name: "CheckBadgeIcon" },
  { component: CheckCircleIcon, name: "CheckCircleIcon" },
  { component: CheckIcon, name: "CheckIcon" },
  { component: ChevronDoubleDownIcon, name: "ChevronDoubleDownIcon" },
  { component: ChevronDoubleLeftIcon, name: "ChevronDoubleLeftIcon" },
  { component: ChevronDoubleRightIcon, name: "ChevronDoubleRightIcon" },
  { component: ChevronDoubleUpIcon, name: "ChevronDoubleUpIcon" },
  { component: ChevronDownIcon, name: "ChevronDownIcon" },
  { component: ChevronLeftIcon, name: "ChevronLeftIcon" },
  { component: ChevronRightIcon, name: "ChevronRightIcon" },
  { component: ChevronUpDownIcon, name: "ChevronUpDownIcon" },
  { component: ChevronUpIcon, name: "ChevronUpIcon" },
  { component: CircleStackIcon, name: "CircleStackIcon" },
  { component: ClipboardDocumentCheckIcon, name: "ClipboardDocumentCheckIcon" },
  { component: ClipboardDocumentListIcon, name: "ClipboardDocumentListIcon" },
  { component: ClipboardDocumentIcon, name: "ClipboardDocumentIcon" },
  { component: ClipboardIcon, name: "ClipboardIcon" },
  { component: ClockIcon, name: "ClockIcon" },
  { component: CloudArrowDownIcon, name: "CloudArrowDownIcon" },
  { component: CloudArrowUpIcon, name: "CloudArrowUpIcon" },
  { component: CloudIcon, name: "CloudIcon" },
  { component: CodeBracketSquareIcon, name: "CodeBracketSquareIcon" },
  { component: CodeBracketIcon, name: "CodeBracketIcon" },
  { component: Cog6ToothIcon, name: "Cog6ToothIcon" },
  { component: Cog8ToothIcon, name: "Cog8ToothIcon" },
  { component: CogIcon, name: "CogIcon" },
  { component: CommandLineIcon, name: "CommandLineIcon" },
  { component: ComputerDesktopIcon, name: "ComputerDesktopIcon" },
  { component: CpuChipIcon, name: "CpuChipIcon" },
  { component: CreditCardIcon, name: "CreditCardIcon" },
  { component: CubeTransparentIcon, name: "CubeTransparentIcon" },
  { component: CubeIcon, name: "CubeIcon" },
  { component: CurrencyBangladeshiIcon, name: "CurrencyBangladeshiIcon" },
  { component: CurrencyDollarIcon, name: "CurrencyDollarIcon" },
  { component: CurrencyEuroIcon, name: "CurrencyEuroIcon" },
  { component: CurrencyPoundIcon, name: "CurrencyPoundIcon" },
  { component: CurrencyRupeeIcon, name: "CurrencyRupeeIcon" },
  { component: CurrencyYenIcon, name: "CurrencyYenIcon" },
  { component: CursorArrowRaysIcon, name: "CursorArrowRaysIcon" },
  { component: CursorArrowRippleIcon, name: "CursorArrowRippleIcon" },
  { component: DevicePhoneMobileIcon, name: "DevicePhoneMobileIcon" },
  { component: DeviceTabletIcon, name: "DeviceTabletIcon" },
  { component: DocumentArrowDownIcon, name: "DocumentArrowDownIcon" },
  { component: DocumentArrowUpIcon, name: "DocumentArrowUpIcon" },
  { component: DocumentChartBarIcon, name: "DocumentChartBarIcon" },
  { component: DocumentCheckIcon, name: "DocumentCheckIcon" },
  { component: DocumentDuplicateIcon, name: "DocumentDuplicateIcon" },
  {
    component: DocumentMagnifyingGlassIcon,
    name: "DocumentMagnifyingGlassIcon",
  },
  { component: DocumentMinusIcon, name: "DocumentMinusIcon" },
  { component: DocumentPlusIcon, name: "DocumentPlusIcon" },
  { component: DocumentTextIcon, name: "DocumentTextIcon" },
  { component: DocumentIcon, name: "DocumentIcon" },
  {
    component: EllipsisHorizontalCircleIcon,
    name: "EllipsisHorizontalCircleIcon",
  },
  { component: EllipsisHorizontalIcon, name: "EllipsisHorizontalIcon" },
  { component: EllipsisVerticalIcon, name: "EllipsisVerticalIcon" },
  { component: EnvelopeOpenIcon, name: "EnvelopeOpenIcon" },
  { component: EnvelopeIcon, name: "EnvelopeIcon" },
  { component: ExclamationCircleIcon, name: "ExclamationCircleIcon" },
  { component: ExclamationTriangleIcon, name: "ExclamationTriangleIcon" },
  { component: EyeDropperIcon, name: "EyeDropperIcon" },
  { component: EyeSlashIcon, name: "EyeSlashIcon" },
  { component: EyeIcon, name: "EyeIcon" },
  { component: FaceFrownIcon, name: "FaceFrownIcon" },
  { component: FaceSmileIcon, name: "FaceSmileIcon" },
  { component: FilmIcon, name: "FilmIcon" },
  { component: FingerPrintIcon, name: "FingerPrintIcon" },
  { component: FireIcon, name: "FireIcon" },
  { component: FlagIcon, name: "FlagIcon" },
  { component: FolderArrowDownIcon, name: "FolderArrowDownIcon" },
  { component: FolderMinusIcon, name: "FolderMinusIcon" },
  { component: FolderOpenIcon, name: "FolderOpenIcon" },
  { component: FolderPlusIcon, name: "FolderPlusIcon" },
  { component: FolderIcon, name: "FolderIcon" },
  { component: ForwardIcon, name: "ForwardIcon" },
  { component: FunnelIcon, name: "FunnelIcon" },
  { component: GifIcon, name: "GifIcon" },
  { component: GiftTopIcon, name: "GiftTopIcon" },
  { component: GiftIcon, name: "GiftIcon" },
  { component: GlobeAltIcon, name: "GlobeAltIcon" },
  { component: GlobeAmericasIcon, name: "GlobeAmericasIcon" },
  { component: GlobeAsiaAustraliaIcon, name: "GlobeAsiaAustraliaIcon" },
  { component: GlobeEuropeAfricaIcon, name: "GlobeEuropeAfricaIcon" },
  { component: HandRaisedIcon, name: "HandRaisedIcon" },
  { component: HandThumbDownIcon, name: "HandThumbDownIcon" },
  { component: HandThumbUpIcon, name: "HandThumbUpIcon" },
  { component: HashtagIcon, name: "HashtagIcon" },
  { component: HeartIcon, name: "HeartIcon" },
  { component: HomeModernIcon, name: "HomeModernIcon" },
  { component: HomeIcon, name: "HomeIcon" },
  { component: IdentificationIcon, name: "IdentificationIcon" },
  { component: InboxArrowDownIcon, name: "InboxArrowDownIcon" },
  { component: InboxStackIcon, name: "InboxStackIcon" },
  { component: InboxIcon, name: "InboxIcon" },
  { component: InformationCircleIcon, name: "InformationCircleIcon" },
  { component: KeyIcon, name: "KeyIcon" },
  { component: LanguageIcon, name: "LanguageIcon" },
  { component: LifebuoyIcon, name: "LifebuoyIcon" },
  { component: LightBulbIcon, name: "LightBulbIcon" },
  { component: LinkIcon, name: "LinkIcon" },
  { component: ListBulletIcon, name: "ListBulletIcon" },
  { component: LockClosedIcon, name: "LockClosedIcon" },
  { component: LockOpenIcon, name: "LockOpenIcon" },
  { component: MagnifyingGlassCircleIcon, name: "MagnifyingGlassCircleIcon" },
  { component: MagnifyingGlassMinusIcon, name: "MagnifyingGlassMinusIcon" },
  { component: MagnifyingGlassPlusIcon, name: "MagnifyingGlassPlusIcon" },
  { component: MagnifyingGlassIcon, name: "MagnifyingGlassIcon" },
  { component: MapPinIcon, name: "MapPinIcon" },
  { component: MapIcon, name: "MapIcon" },
  { component: MegaphoneIcon, name: "MegaphoneIcon" },
  { component: MicrophoneIcon, name: "MicrophoneIcon" },
  { component: MinusCircleIcon, name: "MinusCircleIcon" },
  { component: MinusSmallIcon, name: "MinusSmallIcon" },
  { component: MinusIcon, name: "MinusIcon" },
  { component: MoonIcon, name: "MoonIcon" },
  { component: MusicalNoteIcon, name: "MusicalNoteIcon" },
  { component: NewspaperIcon, name: "NewspaperIcon" },
  { component: NoSymbolIcon, name: "NoSymbolIcon" },
  { component: PaintBrushIcon, name: "PaintBrushIcon" },
  { component: PaperAirplaneIcon, name: "PaperAirplaneIcon" },
  { component: PaperClipIcon, name: "PaperClipIcon" },
  { component: PauseCircleIcon, name: "PauseCircleIcon" },
  { component: PauseIcon, name: "PauseIcon" },
  { component: PencilSquareIcon, name: "PencilSquareIcon" },
  { component: PencilIcon, name: "PencilIcon" },
  { component: PhoneArrowDownLeftIcon, name: "PhoneArrowDownLeftIcon" },
  { component: PhoneArrowUpRightIcon, name: "PhoneArrowUpRightIcon" },
  { component: PhoneXMarkIcon, name: "PhoneXMarkIcon" },
  { component: PhoneIcon, name: "PhoneIcon" },
  { component: PhotoIcon, name: "PhotoIcon" },
  { component: PlayCircleIcon, name: "PlayCircleIcon" },
  { component: PlayPauseIcon, name: "PlayPauseIcon" },
  { component: PlayIcon, name: "PlayIcon" },
  { component: PlusCircleIcon, name: "PlusCircleIcon" },
  { component: PlusSmallIcon, name: "PlusSmallIcon" },
  { component: PlusIcon, name: "PlusIcon" },
  { component: PowerIcon, name: "PowerIcon" },
  { component: PresentationChartBarIcon, name: "PresentationChartBarIcon" },
  { component: PresentationChartLineIcon, name: "PresentationChartLineIcon" },
  { component: PrinterIcon, name: "PrinterIcon" },
  { component: PuzzlePieceIcon, name: "PuzzlePieceIcon" },
  { component: QrCodeIcon, name: "QrCodeIcon" },
  { component: QuestionMarkCircleIcon, name: "QuestionMarkCircleIcon" },
  { component: QueueListIcon, name: "QueueListIcon" },
  { component: RadioIcon, name: "RadioIcon" },
  { component: ReceiptPercentIcon, name: "ReceiptPercentIcon" },
  { component: ReceiptRefundIcon, name: "ReceiptRefundIcon" },
  { component: RectangleGroupIcon, name: "RectangleGroupIcon" },
  { component: RectangleStackIcon, name: "RectangleStackIcon" },
  { component: RocketLaunchIcon, name: "RocketLaunchIcon" },
  { component: RssIcon, name: "RssIcon" },
  { component: ScaleIcon, name: "ScaleIcon" },
  { component: ScissorsIcon, name: "ScissorsIcon" },
  { component: ServerStackIcon, name: "ServerStackIcon" },
  { component: ServerIcon, name: "ServerIcon" },
  { component: ShareIcon, name: "ShareIcon" },
  { component: ShieldCheckIcon, name: "ShieldCheckIcon" },
  { component: ShieldExclamationIcon, name: "ShieldExclamationIcon" },
  { component: ShoppingBagIcon, name: "ShoppingBagIcon" },
  { component: ShoppingCartIcon, name: "ShoppingCartIcon" },
  { component: SignalSlashIcon, name: "SignalSlashIcon" },
  { component: SignalIcon, name: "SignalIcon" },
  { component: SparklesIcon, name: "SparklesIcon" },
  { component: SpeakerWaveIcon, name: "SpeakerWaveIcon" },
  { component: SpeakerXMarkIcon, name: "SpeakerXMarkIcon" },
  { component: Square2StackIcon, name: "Square2StackIcon" },
  { component: Square3Stack3DIcon, name: "Square3Stack3DIcon" },
  { component: Squares2X2Icon, name: "Squares2X2Icon" },
  { component: SquaresPlusIcon, name: "SquaresPlusIcon" },
  { component: StarIcon, name: "StarIcon" },
  { component: StopCircleIcon, name: "StopCircleIcon" },
  { component: StopIcon, name: "StopIcon" },
  { component: SunIcon, name: "SunIcon" },
  { component: SwatchIcon, name: "SwatchIcon" },
  { component: TableCellsIcon, name: "TableCellsIcon" },
  { component: TagIcon, name: "TagIcon" },
  { component: TicketIcon, name: "TicketIcon" },
  { component: TrashIcon, name: "TrashIcon" },
  { component: TrophyIcon, name: "TrophyIcon" },
  { component: TruckIcon, name: "TruckIcon" },
  { component: TvIcon, name: "TvIcon" },
  { component: UserCircleIcon, name: "UserCircleIcon" },
  { component: UserGroupIcon, name: "UserGroupIcon" },
  { component: UserMinusIcon, name: "UserMinusIcon" },
  { component: UserPlusIcon, name: "UserPlusIcon" },
  { component: UserIcon, name: "UserIcon" },
  { component: UsersIcon, name: "UsersIcon" },
  { component: VariableIcon, name: "VariableIcon" },
  { component: VideoCameraSlashIcon, name: "VideoCameraSlashIcon" },
  { component: VideoCameraIcon, name: "VideoCameraIcon" },
  { component: ViewColumnsIcon, name: "ViewColumnsIcon" },
  { component: ViewfinderCircleIcon, name: "ViewfinderCircleIcon" },
  { component: WalletIcon, name: "WalletIcon" },
  { component: WifiIcon, name: "WifiIcon" },
  { component: WindowIcon, name: "WindowIcon" },
  { component: WrenchScrewdriverIcon, name: "WrenchScrewdriverIcon" },
  { component: WrenchIcon, name: "WrenchIcon" },
  { component: XCircleIcon, name: "XCircleIcon" },
  { component: XMarkIcon, name: "XMarkIcon" },
];

type Props = {
  defaultIcon?: string;
};

export default function SelectIcon({ defaultIcon = "" }: Props) {
  const [selected, setSelected] = useState(
    icons.find((i) => i.name === defaultIcon) || icons[0]
  );

  return (
    <>
      <input
        type="text"
        id="icon"
        name="icon"
        value={selected.name}
        className="hidden"
        required={false}
      />
      <Listbox value={selected} onChange={setSelected}>
        {({ open }) => (
          <>
            <div className="relative mt-2">
              <Listbox.Button className="relative w-full cursor-default rounded-md bg-white py-1.5 pl-3 pr-10 text-left text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:outline-none focus:ring-2 focus:ring-indigo-500 sm:text-sm sm:leading-6">
                <span className="flex items-center">
                  <selected.component className="h-5 w-5 flex-shrink-0 rounded-full" />
                  <span className="ml-3 block truncate">{selected.name}</span>
                </span>
                <span className="pointer-events-none absolute inset-y-0 right-0 ml-3 flex items-center pr-2">
                  <ChevronUpDownIcon
                    className="h-5 w-5 text-gray-400"
                    aria-hidden="true"
                  />
                </span>
              </Listbox.Button>

              <Transition
                show={open}
                as={Fragment}
                leave="transition ease-in duration-100"
                leaveFrom="opacity-100"
                leaveTo="opacity-0"
              >
                <Listbox.Options className="absolute z-10 mt-1 max-h-56 w-full overflow-auto rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm">
                  {icons.map((icon) => (
                    <Listbox.Option
                      key={icon.name}
                      className={({ active }) =>
                        classNames(
                          active ? "bg-indigo-600 text-white" : "text-gray-900",
                          "relative cursor-default select-none py-2 pl-3 pr-9"
                        )
                      }
                      value={icon}
                    >
                      {({ selected, active }) => (
                        <>
                          <div className="flex items-center">
                            <icon.component className="h-5 w-5 flex-shrink-0 rounded-full" />
                            <span
                              className={classNames(
                                selected ? "font-semibold" : "font-normal",
                                "ml-3 block truncate"
                              )}
                            >
                              {icon.name}
                            </span>
                          </div>

                          {selected ? (
                            <span
                              className={classNames(
                                active ? "text-white" : "text-indigo-600",
                                "absolute inset-y-0 right-0 flex items-center pr-4"
                              )}
                            >
                              <CheckIcon
                                className="h-5 w-5"
                                aria-hidden="true"
                              />
                            </span>
                          ) : null}
                        </>
                      )}
                    </Listbox.Option>
                  ))}
                </Listbox.Options>
              </Transition>
            </div>
          </>
        )}
      </Listbox>
    </>
  );
}
